import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://yhquuorlvvnunaedqbdj.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlocXV1b3JsdnZudW5hZWRxYmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MjEyNDIsImV4cCI6MjA1NDA5NzI0Mn0.SVno8nqP7OzObg02PWXcBkABQ7TTrfq6tolxxq1Z8kc')